project_id = "mpbcehvytmuuqrabxcse"

[functions.request-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.exchange-session]
verify_jwt = false

[functions.admin-verify-otp]
verify_jwt = false

[functions.create-test-admin]
verify_jwt = false
